/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by apiregister-gen. Do not edit it manually!

package v1alpha1

import (
	"github.com/cloudfoundry-incubator/service-fabrik-apiserver/pkg/apis/backup"
	"github.com/kubernetes-incubator/apiserver-builder/pkg/builders"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

var (
	backupBOSHBackupRestoreStorage = builders.NewApiResource( // Resource status endpoint
		backup.InternalBOSHBackupRestore,
		BOSHBackupRestoreSchemeFns{},
		func() runtime.Object { return &BOSHBackupRestore{} },     // Register versioned resource
		func() runtime.Object { return &BOSHBackupRestoreList{} }, // Register versioned resource list
		&BOSHBackupRestoreStrategy{builders.StorageStrategySingleton},
	)
	ApiVersion = builders.NewApiVersion("backup.servicefabrik.io", "v1alpha1").WithResources(
		backupBOSHBackupRestoreStorage,
		builders.NewApiResource( // Resource status endpoint
			backup.InternalBOSHBackupRestoreStatus,
			BOSHBackupRestoreSchemeFns{},
			func() runtime.Object { return &BOSHBackupRestore{} },     // Register versioned resource
			func() runtime.Object { return &BOSHBackupRestoreList{} }, // Register versioned resource list
			&BOSHBackupRestoreStatusStrategy{builders.StatusStorageStrategySingleton},
		))

	// Required by code generated by go2idl
	AddToScheme        = ApiVersion.SchemaBuilder.AddToScheme
	SchemeBuilder      = ApiVersion.SchemaBuilder
	localSchemeBuilder = &SchemeBuilder
	SchemeGroupVersion = ApiVersion.GroupVersion
)

// Required by code generated by go2idl
// Kind takes an unqualified kind and returns a Group qualified GroupKind
func Kind(kind string) schema.GroupKind {
	return SchemeGroupVersion.WithKind(kind).GroupKind()
}

// Required by code generated by go2idl
// Resource takes an unqualified resource and returns a Group qualified GroupResource
func Resource(resource string) schema.GroupResource {
	return SchemeGroupVersion.WithResource(resource).GroupResource()
}

//
// BOSHBackupRestore Functions and Structs
//
// +k8s:deepcopy-gen=false
type BOSHBackupRestoreSchemeFns struct {
	builders.DefaultSchemeFns
}

// +k8s:deepcopy-gen=false
type BOSHBackupRestoreStrategy struct {
	builders.DefaultStorageStrategy
}

// +k8s:deepcopy-gen=false
type BOSHBackupRestoreStatusStrategy struct {
	builders.DefaultStatusStorageStrategy
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type BOSHBackupRestoreList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []BOSHBackupRestore `json:"items"`
}
