// +build !ignore_autogenerated

//TODO copyright header

// This file was autogenerated by conversion-gen. Do not edit it manually!

package v1alpha1

import (
	backup "github.com/cloudfoundry-incubator/service-fabrik-apiserver/pkg/apis/backup"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	unsafe "unsafe"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1alpha1_BOSHBackupRestore_To_backup_BOSHBackupRestore,
		Convert_backup_BOSHBackupRestore_To_v1alpha1_BOSHBackupRestore,
		Convert_v1alpha1_BOSHBackupRestoreList_To_backup_BOSHBackupRestoreList,
		Convert_backup_BOSHBackupRestoreList_To_v1alpha1_BOSHBackupRestoreList,
		Convert_v1alpha1_BOSHBackupRestoreSpec_To_backup_BOSHBackupRestoreSpec,
		Convert_backup_BOSHBackupRestoreSpec_To_v1alpha1_BOSHBackupRestoreSpec,
		Convert_v1alpha1_BOSHBackupRestoreStatus_To_backup_BOSHBackupRestoreStatus,
		Convert_backup_BOSHBackupRestoreStatus_To_v1alpha1_BOSHBackupRestoreStatus,
		Convert_v1alpha1_BOSHBackupRestoreStatusStrategy_To_backup_BOSHBackupRestoreStatusStrategy,
		Convert_backup_BOSHBackupRestoreStatusStrategy_To_v1alpha1_BOSHBackupRestoreStatusStrategy,
		Convert_v1alpha1_BOSHBackupRestoreStrategy_To_backup_BOSHBackupRestoreStrategy,
		Convert_backup_BOSHBackupRestoreStrategy_To_v1alpha1_BOSHBackupRestoreStrategy,
	)
}

func autoConvert_v1alpha1_BOSHBackupRestore_To_backup_BOSHBackupRestore(in *BOSHBackupRestore, out *backup.BOSHBackupRestore, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_BOSHBackupRestoreSpec_To_backup_BOSHBackupRestoreSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_BOSHBackupRestoreStatus_To_backup_BOSHBackupRestoreStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_BOSHBackupRestore_To_backup_BOSHBackupRestore is an autogenerated conversion function.
func Convert_v1alpha1_BOSHBackupRestore_To_backup_BOSHBackupRestore(in *BOSHBackupRestore, out *backup.BOSHBackupRestore, s conversion.Scope) error {
	return autoConvert_v1alpha1_BOSHBackupRestore_To_backup_BOSHBackupRestore(in, out, s)
}

func autoConvert_backup_BOSHBackupRestore_To_v1alpha1_BOSHBackupRestore(in *backup.BOSHBackupRestore, out *BOSHBackupRestore, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_backup_BOSHBackupRestoreSpec_To_v1alpha1_BOSHBackupRestoreSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_backup_BOSHBackupRestoreStatus_To_v1alpha1_BOSHBackupRestoreStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_backup_BOSHBackupRestore_To_v1alpha1_BOSHBackupRestore is an autogenerated conversion function.
func Convert_backup_BOSHBackupRestore_To_v1alpha1_BOSHBackupRestore(in *backup.BOSHBackupRestore, out *BOSHBackupRestore, s conversion.Scope) error {
	return autoConvert_backup_BOSHBackupRestore_To_v1alpha1_BOSHBackupRestore(in, out, s)
}

func autoConvert_v1alpha1_BOSHBackupRestoreList_To_backup_BOSHBackupRestoreList(in *BOSHBackupRestoreList, out *backup.BOSHBackupRestoreList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]backup.BOSHBackupRestore)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_BOSHBackupRestoreList_To_backup_BOSHBackupRestoreList is an autogenerated conversion function.
func Convert_v1alpha1_BOSHBackupRestoreList_To_backup_BOSHBackupRestoreList(in *BOSHBackupRestoreList, out *backup.BOSHBackupRestoreList, s conversion.Scope) error {
	return autoConvert_v1alpha1_BOSHBackupRestoreList_To_backup_BOSHBackupRestoreList(in, out, s)
}

func autoConvert_backup_BOSHBackupRestoreList_To_v1alpha1_BOSHBackupRestoreList(in *backup.BOSHBackupRestoreList, out *BOSHBackupRestoreList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]BOSHBackupRestore)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_backup_BOSHBackupRestoreList_To_v1alpha1_BOSHBackupRestoreList is an autogenerated conversion function.
func Convert_backup_BOSHBackupRestoreList_To_v1alpha1_BOSHBackupRestoreList(in *backup.BOSHBackupRestoreList, out *BOSHBackupRestoreList, s conversion.Scope) error {
	return autoConvert_backup_BOSHBackupRestoreList_To_v1alpha1_BOSHBackupRestoreList(in, out, s)
}

func autoConvert_v1alpha1_BOSHBackupRestoreSpec_To_backup_BOSHBackupRestoreSpec(in *BOSHBackupRestoreSpec, out *backup.BOSHBackupRestoreSpec, s conversion.Scope) error {
	out.Options = in.Options
	return nil
}

// Convert_v1alpha1_BOSHBackupRestoreSpec_To_backup_BOSHBackupRestoreSpec is an autogenerated conversion function.
func Convert_v1alpha1_BOSHBackupRestoreSpec_To_backup_BOSHBackupRestoreSpec(in *BOSHBackupRestoreSpec, out *backup.BOSHBackupRestoreSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_BOSHBackupRestoreSpec_To_backup_BOSHBackupRestoreSpec(in, out, s)
}

func autoConvert_backup_BOSHBackupRestoreSpec_To_v1alpha1_BOSHBackupRestoreSpec(in *backup.BOSHBackupRestoreSpec, out *BOSHBackupRestoreSpec, s conversion.Scope) error {
	out.Options = in.Options
	return nil
}

// Convert_backup_BOSHBackupRestoreSpec_To_v1alpha1_BOSHBackupRestoreSpec is an autogenerated conversion function.
func Convert_backup_BOSHBackupRestoreSpec_To_v1alpha1_BOSHBackupRestoreSpec(in *backup.BOSHBackupRestoreSpec, out *BOSHBackupRestoreSpec, s conversion.Scope) error {
	return autoConvert_backup_BOSHBackupRestoreSpec_To_v1alpha1_BOSHBackupRestoreSpec(in, out, s)
}

func autoConvert_v1alpha1_BOSHBackupRestoreStatus_To_backup_BOSHBackupRestoreStatus(in *BOSHBackupRestoreStatus, out *backup.BOSHBackupRestoreStatus, s conversion.Scope) error {
	out.State = in.State
	return nil
}

// Convert_v1alpha1_BOSHBackupRestoreStatus_To_backup_BOSHBackupRestoreStatus is an autogenerated conversion function.
func Convert_v1alpha1_BOSHBackupRestoreStatus_To_backup_BOSHBackupRestoreStatus(in *BOSHBackupRestoreStatus, out *backup.BOSHBackupRestoreStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_BOSHBackupRestoreStatus_To_backup_BOSHBackupRestoreStatus(in, out, s)
}

func autoConvert_backup_BOSHBackupRestoreStatus_To_v1alpha1_BOSHBackupRestoreStatus(in *backup.BOSHBackupRestoreStatus, out *BOSHBackupRestoreStatus, s conversion.Scope) error {
	out.State = in.State
	return nil
}

// Convert_backup_BOSHBackupRestoreStatus_To_v1alpha1_BOSHBackupRestoreStatus is an autogenerated conversion function.
func Convert_backup_BOSHBackupRestoreStatus_To_v1alpha1_BOSHBackupRestoreStatus(in *backup.BOSHBackupRestoreStatus, out *BOSHBackupRestoreStatus, s conversion.Scope) error {
	return autoConvert_backup_BOSHBackupRestoreStatus_To_v1alpha1_BOSHBackupRestoreStatus(in, out, s)
}

func autoConvert_v1alpha1_BOSHBackupRestoreStatusStrategy_To_backup_BOSHBackupRestoreStatusStrategy(in *BOSHBackupRestoreStatusStrategy, out *backup.BOSHBackupRestoreStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_v1alpha1_BOSHBackupRestoreStatusStrategy_To_backup_BOSHBackupRestoreStatusStrategy is an autogenerated conversion function.
func Convert_v1alpha1_BOSHBackupRestoreStatusStrategy_To_backup_BOSHBackupRestoreStatusStrategy(in *BOSHBackupRestoreStatusStrategy, out *backup.BOSHBackupRestoreStatusStrategy, s conversion.Scope) error {
	return autoConvert_v1alpha1_BOSHBackupRestoreStatusStrategy_To_backup_BOSHBackupRestoreStatusStrategy(in, out, s)
}

func autoConvert_backup_BOSHBackupRestoreStatusStrategy_To_v1alpha1_BOSHBackupRestoreStatusStrategy(in *backup.BOSHBackupRestoreStatusStrategy, out *BOSHBackupRestoreStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_backup_BOSHBackupRestoreStatusStrategy_To_v1alpha1_BOSHBackupRestoreStatusStrategy is an autogenerated conversion function.
func Convert_backup_BOSHBackupRestoreStatusStrategy_To_v1alpha1_BOSHBackupRestoreStatusStrategy(in *backup.BOSHBackupRestoreStatusStrategy, out *BOSHBackupRestoreStatusStrategy, s conversion.Scope) error {
	return autoConvert_backup_BOSHBackupRestoreStatusStrategy_To_v1alpha1_BOSHBackupRestoreStatusStrategy(in, out, s)
}

func autoConvert_v1alpha1_BOSHBackupRestoreStrategy_To_backup_BOSHBackupRestoreStrategy(in *BOSHBackupRestoreStrategy, out *backup.BOSHBackupRestoreStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_v1alpha1_BOSHBackupRestoreStrategy_To_backup_BOSHBackupRestoreStrategy is an autogenerated conversion function.
func Convert_v1alpha1_BOSHBackupRestoreStrategy_To_backup_BOSHBackupRestoreStrategy(in *BOSHBackupRestoreStrategy, out *backup.BOSHBackupRestoreStrategy, s conversion.Scope) error {
	return autoConvert_v1alpha1_BOSHBackupRestoreStrategy_To_backup_BOSHBackupRestoreStrategy(in, out, s)
}

func autoConvert_backup_BOSHBackupRestoreStrategy_To_v1alpha1_BOSHBackupRestoreStrategy(in *backup.BOSHBackupRestoreStrategy, out *BOSHBackupRestoreStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_backup_BOSHBackupRestoreStrategy_To_v1alpha1_BOSHBackupRestoreStrategy is an autogenerated conversion function.
func Convert_backup_BOSHBackupRestoreStrategy_To_v1alpha1_BOSHBackupRestoreStrategy(in *backup.BOSHBackupRestoreStrategy, out *BOSHBackupRestoreStrategy, s conversion.Scope) error {
	return autoConvert_backup_BOSHBackupRestoreStrategy_To_v1alpha1_BOSHBackupRestoreStrategy(in, out, s)
}
