//TODO copyright header

// This file was automatically generated by lister-gen

package v1alpha1

// BOSHBackupRestoreListerExpansion allows custom methods to be added to
// BOSHBackupRestoreLister.
type BOSHBackupRestoreListerExpansion interface{}

// BOSHBackupRestoreNamespaceListerExpansion allows custom methods to be added to
// BOSHBackupRestoreNamespaceLister.
type BOSHBackupRestoreNamespaceListerExpansion interface{}
