// +build !ignore_autogenerated

//TODO copyright header

// This file was autogenerated by deepcopy-gen. Do not edit it manually!

package backup

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BOSHBackupRestore) DeepCopyInto(out *BOSHBackupRestore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BOSHBackupRestore.
func (in *BOSHBackupRestore) DeepCopy() *BOSHBackupRestore {
	if in == nil {
		return nil
	}
	out := new(BOSHBackupRestore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BOSHBackupRestore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BOSHBackupRestoreList) DeepCopyInto(out *BOSHBackupRestoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BOSHBackupRestore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BOSHBackupRestoreList.
func (in *BOSHBackupRestoreList) DeepCopy() *BOSHBackupRestoreList {
	if in == nil {
		return nil
	}
	out := new(BOSHBackupRestoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BOSHBackupRestoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BOSHBackupRestoreSpec) DeepCopyInto(out *BOSHBackupRestoreSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BOSHBackupRestoreSpec.
func (in *BOSHBackupRestoreSpec) DeepCopy() *BOSHBackupRestoreSpec {
	if in == nil {
		return nil
	}
	out := new(BOSHBackupRestoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BOSHBackupRestoreStatus) DeepCopyInto(out *BOSHBackupRestoreStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BOSHBackupRestoreStatus.
func (in *BOSHBackupRestoreStatus) DeepCopy() *BOSHBackupRestoreStatus {
	if in == nil {
		return nil
	}
	out := new(BOSHBackupRestoreStatus)
	in.DeepCopyInto(out)
	return out
}
