//TODO copyright header

// This file was automatically generated by informer-gen

package v1alpha1

import (
	backup_v1alpha1 "github.com/cloudfoundry-incubator/service-fabrik-apiserver/pkg/apis/backup/v1alpha1"
	clientset "github.com/cloudfoundry-incubator/service-fabrik-apiserver/pkg/client/clientset_generated/clientset"
	internalinterfaces "github.com/cloudfoundry-incubator/service-fabrik-apiserver/pkg/client/informers_generated/externalversions/internalinterfaces"
	v1alpha1 "github.com/cloudfoundry-incubator/service-fabrik-apiserver/pkg/client/listers_generated/backup/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// BOSHBackupRestoreInformer provides access to a shared informer and lister for
// BOSHBackupRestores.
type BOSHBackupRestoreInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.BOSHBackupRestoreLister
}

type bOSHBackupRestoreInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewBOSHBackupRestoreInformer constructs a new informer for BOSHBackupRestore type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewBOSHBackupRestoreInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredBOSHBackupRestoreInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredBOSHBackupRestoreInformer constructs a new informer for BOSHBackupRestore type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredBOSHBackupRestoreInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.BackupV1alpha1().BOSHBackupRestores(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.BackupV1alpha1().BOSHBackupRestores(namespace).Watch(options)
			},
		},
		&backup_v1alpha1.BOSHBackupRestore{},
		resyncPeriod,
		indexers,
	)
}

func (f *bOSHBackupRestoreInformer) defaultInformer(client clientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredBOSHBackupRestoreInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *bOSHBackupRestoreInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&backup_v1alpha1.BOSHBackupRestore{}, f.defaultInformer)
}

func (f *bOSHBackupRestoreInformer) Lister() v1alpha1.BOSHBackupRestoreLister {
	return v1alpha1.NewBOSHBackupRestoreLister(f.Informer().GetIndexer())
}
