//TODO copyright header

// This file was automatically generated by informer-gen

package internalversion

import (
	backup "github.com/cloudfoundry-incubator/service-fabrik-apiserver/pkg/apis/backup"
	internalclientset "github.com/cloudfoundry-incubator/service-fabrik-apiserver/pkg/client/clientset_generated/internalclientset"
	internalinterfaces "github.com/cloudfoundry-incubator/service-fabrik-apiserver/pkg/client/informers_generated/internalversion/internalinterfaces"
	internalversion "github.com/cloudfoundry-incubator/service-fabrik-apiserver/pkg/client/listers_generated/backup/internalversion"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// BOSHBackupRestoreInformer provides access to a shared informer and lister for
// BOSHBackupRestores.
type BOSHBackupRestoreInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() internalversion.BOSHBackupRestoreLister
}

type bOSHBackupRestoreInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewBOSHBackupRestoreInformer constructs a new informer for BOSHBackupRestore type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewBOSHBackupRestoreInformer(client internalclientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredBOSHBackupRestoreInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredBOSHBackupRestoreInformer constructs a new informer for BOSHBackupRestore type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredBOSHBackupRestoreInformer(client internalclientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.Backup().BOSHBackupRestores(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.Backup().BOSHBackupRestores(namespace).Watch(options)
			},
		},
		&backup.BOSHBackupRestore{},
		resyncPeriod,
		indexers,
	)
}

func (f *bOSHBackupRestoreInformer) defaultInformer(client internalclientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredBOSHBackupRestoreInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *bOSHBackupRestoreInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&backup.BOSHBackupRestore{}, f.defaultInformer)
}

func (f *bOSHBackupRestoreInformer) Lister() internalversion.BOSHBackupRestoreLister {
	return internalversion.NewBOSHBackupRestoreLister(f.Informer().GetIndexer())
}
