//TODO copyright header

// This file was automatically generated by lister-gen

package internalversion

import (
	backup "github.com/cloudfoundry-incubator/service-fabrik-apiserver/pkg/apis/backup"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// BOSHBackupRestoreLister helps list BOSHBackupRestores.
type BOSHBackupRestoreLister interface {
	// List lists all BOSHBackupRestores in the indexer.
	List(selector labels.Selector) (ret []*backup.BOSHBackupRestore, err error)
	// BOSHBackupRestores returns an object that can list and get BOSHBackupRestores.
	BOSHBackupRestores(namespace string) BOSHBackupRestoreNamespaceLister
	BOSHBackupRestoreListerExpansion
}

// bOSHBackupRestoreLister implements the BOSHBackupRestoreLister interface.
type bOSHBackupRestoreLister struct {
	indexer cache.Indexer
}

// NewBOSHBackupRestoreLister returns a new BOSHBackupRestoreLister.
func NewBOSHBackupRestoreLister(indexer cache.Indexer) BOSHBackupRestoreLister {
	return &bOSHBackupRestoreLister{indexer: indexer}
}

// List lists all BOSHBackupRestores in the indexer.
func (s *bOSHBackupRestoreLister) List(selector labels.Selector) (ret []*backup.BOSHBackupRestore, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*backup.BOSHBackupRestore))
	})
	return ret, err
}

// BOSHBackupRestores returns an object that can list and get BOSHBackupRestores.
func (s *bOSHBackupRestoreLister) BOSHBackupRestores(namespace string) BOSHBackupRestoreNamespaceLister {
	return bOSHBackupRestoreNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// BOSHBackupRestoreNamespaceLister helps list and get BOSHBackupRestores.
type BOSHBackupRestoreNamespaceLister interface {
	// List lists all BOSHBackupRestores in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*backup.BOSHBackupRestore, err error)
	// Get retrieves the BOSHBackupRestore from the indexer for a given namespace and name.
	Get(name string) (*backup.BOSHBackupRestore, error)
	BOSHBackupRestoreNamespaceListerExpansion
}

// bOSHBackupRestoreNamespaceLister implements the BOSHBackupRestoreNamespaceLister
// interface.
type bOSHBackupRestoreNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all BOSHBackupRestores in the indexer for a given namespace.
func (s bOSHBackupRestoreNamespaceLister) List(selector labels.Selector) (ret []*backup.BOSHBackupRestore, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*backup.BOSHBackupRestore))
	})
	return ret, err
}

// Get retrieves the BOSHBackupRestore from the indexer for a given namespace and name.
func (s bOSHBackupRestoreNamespaceLister) Get(name string) (*backup.BOSHBackupRestore, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(backup.Resource("boshbackuprestore"), name)
	}
	return obj.(*backup.BOSHBackupRestore), nil
}
